USGS-CMG/stglib

stglib/core/utils.py
stglib/rsk/nc2waves.py
stglib/rsk/rsk2cdf.py

Included functionality for burst, continuous and duo/virtuoso.
Temperature from duo get's parsed same as pressure bursts.
Three lines have been added to instrument config files 
instrument_type: 'rbr_duo'     #(rbr_virtuoso,rbr_duo) 
recording_type: 'continuous'   # (burst, continuous)
wave_interval: 1800              # [sec] interval for wave statistics for continuous data
If lines are missing default is Virtuoso in Burst mode.
Tested for
- RBRduo continuous. 
Untested for
- virtuoso burst (recommend this be checked, can you check Dan?)
- virtuoso continuous
- rbrduo burst

Included functionality for burst, continuous and duo/virtuoso

---

doc/contributing.rst
doc/doc-requirements.yml
doc/index.rst
doc/make.bat

Here is a file for the docs that describes how to contribute.
- A requirements file, doc-requirements.yml was added, specific to building docs.  This was provided so that conda can build an environment for making docs
- A make.bat file was added so that docs can be built on windows machines.
- index.rst was updated to include contributing.rst
I have tested the docs build and it works.

Add documentation to address how to contribute to stglib

---

stglib/aqd/qaqc.py

I have AQD datasets with 34 bins. All bins are underwater at some point during data collection. 
So, after trimming via 'water level sl', there are no bins that have only NaNs. 
After velocity trimming, qaqc.trim_vel looks for the last full bin with values, and cuts out bins with only NaNs:
`lastbin = np.argmin(np.all(np.isnan(ds[data_vars[0]].values), axis=0) == False)`
`ds = ds.isel(bindist=slice(0, lastbin))`
Because the AQD data I am working with have no bins above water at all times, it cannot find the last full bin and sets lastbin to 0. 
This causes the function to delete all of the bins and runaqdcdf2nc.py raises an error. 
I added: `if not lastbin == 0:` and it now works. 
There could be another solution to this problem? 
If you would like me to send files please let me know. …

qaqc.trim_vel: if all bins are underwater, do not slice bindist

---

stglib/exo.py

Fix non-UDUNIT units in exo.py by setting to "1" and add "units_note:" variable attribute in those instances to describe units. Fix issue with _FillValue attribute showing up in some coordinate variables. Checked formatting with black and ran test_scripts.

updates to exo.py

---

stglib/core/qaqc.py
stglib/eofe.py
stglib/tests/data/1123Aea_example_config.yaml
stglib/tests/data/glob_att1123A_msl.txt

Modify eofe.py to include trimming of data by new "trim_alt" def and existing code in qaqc.py and others. Add def to qaqc.py to trim 1d variable by maximum absolute difference method. New trim_alt def in eofe.py allows "altitude" method to trim data when out of water during a deployment, e.g. where instrument is exposed during low water events, or just low tides, and also allows clipping of extra bins as specified by user in config yaml file. Tests updated to include new capabilities.

Add EofE qaqc capabilities

---

stglib/core/utils.py
stglib/tests/data/1151Bexo_config.yaml

Round time units to 1 second in Clock_Drift part of utils.shift_time def. This necessary because time index is saved as dtype 'i4' in the CF netcdf files for data release (.nc files).

Fixclockdrift

---

stglib/eco.py
stglib/tests/data/11032Decn_config.yaml

Add new qaqc function calls and edit order of calls so that difference filtering fcns are called first.

Edits to QA/QC for ECO instruments

---

stglib/core/qaqc.py
stglib/eco.py
stglib/tests/data/11032Decn_config.yaml

Add ability to trim variables with companion standard deviation variables using user threshold for the ratio of standard deviation to variable value. Made generic so will work when invoked as long as there is a companion variable in the dataset with name format var + "_std". Also fixed issue with existing trim_max_std function and made it non-specific as well (previously had "Turb_std" hard coded).

add trim by stddev ratio

---

stglib/rsk/cdf2nc.py
stglib/rsk/csv2cdf.py

Add ability to write out the continuous RBR data to CF netCDF file and also preserve shaping of continuous data into wave burst if wave_interval attribute is specified and write out CF netCDF file for both in a single workflow. Had to make coordinate variable "time" a dtype = "double" for continuous data netCDF file (+ 'cont-cal.nc'), since int64 not allowed currently . Also edited rsk/cdf2nc.trim_min to handle when no sample dim exists (i.e. for continuous data). New code was tested on 2 separate datasets (1 using virtuosos D|fast 12 and other solo3d), and test_scripts.py was run to make sure code was not broken with existing tests/data.

rbrcontncout

---

stglib/exo.py

Update EXO variable attributes to be consistent across like variables and to follow CF conventions if available. Try to use MKS (meters-seconds-kilograms) where possible unless there is a compelling reason not to do so.

update exo variable attributes

---

doc/config.rst
doc/index.rst
doc/sig.rst

Add and update docs for Signature Support. I was unable to built the docs locally. There was an extension error running sphinx (see below).
(stglib-docs) C:\Users\ssuttles\Git\stglib\doc>make html
Running Sphinx v5.0.2
[autosummary] generating autosummary for: aqd.rst, atmos.rst, code.rst, config.rst, contributing.rst, eofe.rst, exo.rst, hobo.rst, index.rst, indexvel.rst, install.rst, iq.rst, overview.rst, rsk.rst, sig.rst, turnaround.rst, vec.rst, wet.rst, wvs.rst, wxt.rst
 
Extension error (sphinx.ext.autosummary):
Handler <function process_generate_options at 0x000002BF905A5EA0> for event 'builder-inited' threw an exception (exception: no module named stglib.aqd.cdf2nc)

Add Signature Support Docs

---

.github/workflows/stglib_test_conda.yml
doc/environment.yml
doc/requirements.txt
requirements.txt
requirements.yml
stglib/core/qaqc.py
stglib/core/utils.py
stglib/sig/mat2cdf.py

On GitHub Actions, Python < 3.11 fails for unknown reasons. Tests on  Windows Python < 3.11 work locally, so removing these tests on GHA.

Exclude older Windows Python versions from GHA tests

---

.gitattributes
stglib/rsk/nc2waves.py
stglib/tests/data/055109_20220808_1605.zip
stglib/tests/data/055109_20220808_1605_config.yaml
stglib/tests/data/gatts_055109_20220808_1605.txt
stglib/tests/test_scripts.py

Added numpy and xarray imports to beginning of nc2waves.py as well as incorporating a continuous dwave dataset to the rsk test.

add imports to nc2wave.py and cont dwave test

---

stglib/aqd/aqdutils.py
stglib/aqd/cdf2nc.py

This PR includes 2 QAQC Aquadopp features in aqdutils:
1. Filling transformed velocities (u,v,w) by an AGC threshold. I did not include filling beam velocities (vel1,vel2,vel3) in the is feature. From what I'm noticing, the beam velocities are always left unfilled. 
2. Filling additional surface bins if trim_method 'water level sl' is not sufficient and some surface velocities are still bad throughout dataset. 
Let me know if you have any suggested changes to how I've written the code/naming of threshold attributes.

Aqd agc slbins

---

stglib/exo.py

Hi Dan, 
The YSI Exo variable "BGA" has been changed to "TAL". This stands for "Total algae phycoerythrin." They are the same variable, just a new name. We made changes in stglib a while back to accommodate the name change. 
However, if an old Exo dataset is processed, stglib will still name the variable BGA (because that is how it is named in the exported .csv file). Steve suggested we keep the name consistent as "TAL." I made some changes so if an old Exo dataset is processed, it will default to renaming BGA to TAL. 
Are you ok with these changes?

Exo TALPE name

---

stglib/core/utils.py
stglib/tests/data/glob_att1123A_msl.txt

Update needed because P_1 variable can and often does include pressure due to things other than sea water (e.g atmosheric pressure). Best practice would be to use the WATER_DEPTH and initial_instrument_height attributes to determine the depth dimension because it is expected that WATER_DEPTH attribute was determined relative to a water level datum (e.g. Mean Sea Level, Local Mean Sea Level, or ground water table).

Update how to determine depth dimension

---

doc/vec.rst

the run file for vector to cdf was listed as "runvechdr2cdf.py".  I don't think that run file exists; instead it should be "runvecdat2cdf.py"  I changed the documentation.

Update vec.rst documentation

---

stglib/iq.py

This pull request includes some minor changes to iq.py:
-Fixed type in Vel_Mean "long_name" attribute
-Changed encoding of time to "i4"
-Added a def to fill Vel_Mean by other velocity variables (since this the mean velocity, should fill during times of other bad beam/bank (left or right) velocity data)

Fill IQ mean velocity and other fixes

---

stglib/eofe.py

Correct sign error in applying initial_instrument_height attribute to the boundary_elevation calculation for Local Mean Sea-Level (LMSL) datum with UP instrument orientation case.

Fix boundary elevation calculation

---

stglib/core/qaqc.py

I'm not sure why we had this constraint, since xarray built-in broadcasting should be able to take care of dimension mismatches (e.g., 1D time and 2D time-sample variables)

Remove constraint on mask variables

---

stglib/rsk/cdf2nc.py
stglib/rsk/csv2cdf.py

Reset row_start and obs indexes after trimming, and add warning message. This makes profiling CTD casts with QAQC applied be more in line with CF Conventions for obs and row_start.

Improve profiling CTD obs and row_start values

---

stglib/core/waves.py

The old way would not properly handle a situation where K_p values were all greater than 0.1. For example, if `Kp = np.array([1, .5, .11])`, then the old way of computing the index, `Kpcutind = np.argmax(Kp <= 0.1)` will return `0`. In this case we want to have the "cutoff" be the entire array, not none of the array. To fix this, we change to `np.nonzero(Kp > 0.1)[0][-1] + 1` which is the index of the last value in the array, plus 1.
If `Kp = np.array([1, .5, .11, .1, .09, .01])`, then the old and new approach both yield `3`.

Fix selection of values that pass the K_p criterion

---

stglib/vec/cdf2nc.py

This approach improves run speed by 50% for a ~10 GB Vector file.
CC @rbales-usgs

Initialize arrays for speed savings

---

stglib/core/qaqc.py
stglib/vec/cdf2nc.py

Added SNR and COR thresholds to fill velocity data. Other minor changes included in this feature branch are: 
- added the ability to use trim_maxabs_diff for burst shaped data
- Changed dtype float64 to float32 to save space and drop file writing time
- removed z dims from variables to save space and drop file writing time (z coordinates still remain)

Vector_thresholds
