stglib/aqd/qaqc.py
=> Raise user-friendly error when encountering an HR dataset (GH4)

stglib/exo.py
=> Add INST_TYPE for exo

stglib/exo.py, stglib/rsk/cdf2nc.py
=> Ensure COMPOSITE attr is set

stglib/core/utils.py, stglib/tests/test_stglib.py
=> Ensure MOORING is string

stglib/aqd/wvscdf2nc.py, stglib/exo.py, stglib/rsk/cdf2nc.py
=> Ensure DELTA_T is written

stglib/aqd/cdf2nc.py, stglib/aqd/qaqc.py, stglib/aqd/wvsnc2diwasp.py
=> Fix bat 106

doc/config.rst
Closes #51. @mmartini-usgs thoughts?
=> update zeroed_pressure docs

scripts/runwxtcdf2nc.py, scripts/runwxtcsv2cdf.py, stglib/core/cmd.py, stglib/tests/data/.gitattributes, stglib/tests/data/glob_att1149.txt, stglib/tests/data/wxt1149_config.yaml, stglib/tests/test_scripts.py, stglib/wxt.py
=> Vaisala met

stglib/aqd/cdf2nc.py, stglib/core/qaqc.py, stglib/eco.py, stglib/exo.py, stglib/rsk/cdf2nc.py
Separated out qaqc code in exo.py and eco.py into new qaqc.py in stglib/stglib/core. Affected files were updated, and standard tests (test_scripts.py) were ran to confirm functionality. Code formatting was checked with Black code formatter.
=> add qaqc.py in core

stglib/wxt.py
Cast global attribute variable "dir_offset" and "magnetic_variation" as floats when used in wind direction calculations in wxt.py. Remove commented out lines. Ran tests test_scripts.py and processed test dataset.
=> fix dtype issue

README.md, doc/code.rst, doc/conf.py, doc/contributing.rst, doc/doc-requirements.yml, doc/eofe.rst, doc/index.rst, doc/install.rst, doc/rsk.rst, doc/wet.rst, setup.py, stglib/wxt.py
Update to new version of sphinx and fix several errors and warnings. Also update URLs.
=> Fix a bunch of sphinx errors and warnings

doc/config.rst, stglib/core/qaqc.py, stglib/tests/data/aqd1121A_config.yaml
Pinging @ssuttles-usgs. I made some code readability edits and confirmed the output is identical with what was produced by your version. Please have a look and let me know what you think.
=> Updates to trim_maxabs_diff_2d for readability, docs, and tests

scripts/runveccdf2nc.py, scripts/runvecdat2cdf.py, setup.py, stglib/__init__.py, stglib/aqd/aqdutils.py, stglib/core/cmd.py, stglib/core/utils.py, stglib/vec/__init__.py, stglib/vec/cdf2nc.py, stglib/vec/dat2cdf.py
Work in progress. Code to process Nortek Vector instruments, largely based off Aquadopp processing workflow.
=> Merge Vector processing code into master

stglib/eofe.py
Updates to "Add EofE qaqc capabilities (PR #85)". In eofe.py, 1) move trim_bad_ens so that it is comes after any difference filtering, and 2) in def trim_alt, add trimming for when altitude is greater than specified range in the instrument settings.
=> update to EofE qaqc

doc/config.rst, stglib/core/utils.py, stglib/tests/data/config_bel5C.yaml, stglib/tests/test_utils.py
Pinging @ssuttles-usgs. Kept ClockError as a static offset and added ClockDrift for a linear drift. Are we happy with these names?
=> Update clock error code to include drift (addresses #44)

stglib/aqd/aqdutils.py, stglib/aqd/wvsnc2waves.py, stglib/core/utils.py, stglib/eco.py, stglib/exo.py, stglib/iq.py, stglib/rsk/cdf2nc.py, stglib/rsk/nc2waves.py
Code that was never being activated since we call ensure_cf() at the very beginning for (nearly) all instruments now.
=> Remove more vestigial EPIC stuff

stglib/rsk/cdf2nc.py, stglib/rsk/nc2waves.py
=> Move RBR wave burst creation to nc2waves.py

stglib/core/utils.py, stglib/sig/cdf2nc.py, stglib/sig/mat2cdf.py, stglib/tests/data/.gitattributes, stglib/tests/data/glob_att1126_sig1.txt, stglib/tests/data/glob_att1126_sig2.txt, stglib/tests/data/mat2/11262sig_0000_6.mat, stglib/tests/data/sig11262_config.yaml, stglib/tests/test_scripts.py
Add support for Burst and IBurst High-Resolution modes (HR), and Echosounder (Echo1) mode. Add manual chunking to cdf datasets imported into sig/cdf2nc.py to allow handling of larger datasets and variables and improve performance of code. Updated tests and tested new functionality locally, but put decorator on test_sig() in test_scripts.py to cause test to be skipped on the pull request.
=> Additional Signature support

stglib/aqd/aqdutils.py, stglib/sig/cdf2nc.py, stglib/sig/mat2cdf.py, stglib/tests/data/sig1126_config.yaml, stglib/tests/test_scripts.py
Add ability to better handle very large datasets, including user specified chunks, displaying dask progress bar when writing out netcdf files, and error handling when trying to make the composite -raw.cdf file. Also added bin_size attribute to signature global attribute output to be consistent with other profiling instruments in stglib. Modified code was reformatted using black.
=> Signature Support updates

doc/config.rst, stglib/eofe.py, stglib/tests/data/1123Aea_example_config.yaml
Change seabed_elevation to boundary_elevation because not always measuring distance to the seabed. Improve finding speed of sound routines to make corrected bin_height and brange estimates. Add ability to change vertical dimension using new config parameter "vert_dim". Add CF compliance check for b-cal.nc file.
=> Updates to EofE  Echologger processing

stglib/vec/cdf2nc.py, stglib/vec/dat2cdf.py
=> Convert AnalogInput from counts to volts

stglib/lisst.py, stglib/tests/data/.gitattributes, stglib/tests/data/L0221705_v2_rs.csv, stglib/tests/data/config_lisst_L0221705.yaml, stglib/tests/data/gatts_lisst_L0221705.txt, stglib/tests/test_scripts.py
Fixes https://github.com/USGS-CMG/stglib/issues/175.
=> Drop vars and add LISST test

stglib/aqd/aqdutils.py, stglib/aqd/hdr2cdf.py, stglib/aqd/hrhdr2cdf.py, stglib/aqd/wvswad2cdf.py, stglib/argonaut.py
=> Update deprecated date_parser to date_format

stglib/aqd/aqdutils.py, stglib/vec/cdf2nc.py, stglib/vec/dat2cdf.py
=> Export distance to boundary.

doc/install.rst
Added update section
mamba activate stglib
mamba update stglib
=> Update to mamba installation instructions

doc/config.rst, stglib/aqd/aqdutils.py, stglib/tests/data/config_nbm22cce01.yaml, stglib/vec/cdf2nc.py
=> Add z dims for analog inputs

stglib/core/utils.py
error in create_z when using D_3 for depth variable
=> Fix typo: P_1ac to D_3

stglib/core/transform.py
Imported inv from numpy.linalg to invert transformation matrix in order to reverse velocity transformation from xyz to beam.
=> import inv from numpy

stglib/aqd/wvsnc2diwasp.py
This brings AQD wavs processing up to date with other instrument workflows
=> Update AQD waves processing
